version: "3.7"
services:
    laravel:
        build:
            context: .
            dockerfile: Docker/dockerfile/app.Dockerfile
        container_name: laravel
        ports:
            - "8002:9000"
        volumes:
            - .:/var/www
        networks:
            - backend

    nginx:
        build:
            context: .
            dockerfile: Docker/dockerfile/nginx.Dockerfile
        container_name: nginx
        ports:
            - "80:80"
        depends_on:
            - laravel
        networks:
            - backend

networks:
    backend:
        driver: bridge
