version: "3"
services:
    app:
        image: johanesrendy/laravel:${IMAGE_VER}
        container_name: laravel
        restart: unless-stopped
        tty: true
        volumes:
            - .env:/var/www/.env
        networks:
            - laravel-net
        environment:
            IMAGE_VER: ${IMAGE_VER}

    nginx:
        image: johanesrendy/laravel-nginx:${IMAGE_VER}
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8002:80"
        depends_on:
            - app
        networks:
            - laravel-net
        environment:
            IMAGE_VER: ${IMAGE_VER}

# Docker Networks
networks:
    laravel-net:
        driver: bridge
