version: "3"

services:
    app:
        image: johanesrendy/laravel:${IMAGE_VER}
        container_name: laravel
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www # Memetakan source code Laravel
            - .env:/var/www/.env # File .env Laravel
        networks:
            - laravel-net
        depends_on:
            - npm # Menunggu npm siap sebelum app dimulai

    nginx:
        image: johanesrendy/laravel-nginx:${IMAGE_VER}
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8005:80" # Port untuk akses Nginx
            - "5173:5173" # Port untuk frontend (Vite)
        depends_on:
            - app # Nginx menunggu app siap
        networks:
            - laravel-net

    npm:
        image: johanesrendy/laravel-npm:${IMAGE_VER}
        container_name: npm
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www # Volume untuk kode frontend
            - /var/www/node_modules
        working_dir: /var/www
        networks:
            - laravel-net
        command: >
            sh -c "sudo rm -rf /var/www/public/hot && npm run dev"

# Docker Networks
networks:
    laravel-net:
        driver: bridge
