version: "3"
services:
    app:
        image: johanesrendy/laravel:${IMAGE_VER}
        container_name: laravel
        restart: unless-stopped
        tty: true
        volumes:
            - .env:/var/www/.env
            - ./your-laravel-app:/var/www/html # Adjust path as needed
        networks:
            - laravel-net
        environment:
            IMAGE_VER: ${IMAGE_VER}
        healthcheck:
            test: ["CMD", "curl", "--silent", "--fail", "http://localhost:9000"]
            interval: 30s
            retries: 3
            timeout: 10s
            start_period: 10s

    nginx:
        image: johanesrendy/laravel-nginx:${IMAGE_VER}
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8003:80"
        depends_on:
            app:
                condition: service_healthy
        networks:
            - laravel-net
        environment:
            IMAGE_VER: ${IMAGE_VER}

# Docker Networks
networks:
    laravel-net:
        driver: bridge
