version: "3"

services:
    app:
        image: johanesrendy/laravel:${IMAGE_VER}
        container_name: laravel
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www # Pastikan source code Laravel ada di dalam container
            - .env:/var/www/.env # Memetakan file .env untuk Laravel
        networks:
            - laravel-net
        environment:
            IMAGE_VER: ${IMAGE_VER}
        depends_on:
            - nginx # Pastikan aplikasi menunggu hingga Nginx siap

    nginx:
        image: johanesrendy/laravel-nginx:${IMAGE_VER}
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8005:80" # Memetakan port 8005 di host ke port 80 di container
            - "5173:5173"
        volumes:
            - .:/var/www # Memetakan source code Laravel di dalam container
            - ./nginx.conf:/etc/nginx/nginx.conf # Memastikan Nginx terkonfigurasi dengan benar
        depends_on:
            - app # Menunggu kontainer aplikasi PHP siap
        networks:
            - laravel-net
        environment:
            IMAGE_VER: ${IMAGE_VER}

# Docker Networks
networks:
    laravel-net:
        driver: bridge
