name: Deploy Application

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_VER environment variable for docker-compose
        run: echo "IMAGE_VER=latest-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/dockerfile/app.Dockerfile
          push: true
          tags: johanesrendy/laravel:${{ env.IMAGE_VER }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/dockerfile/nginx.Dockerfile
          push: true
          tags: johanesrendy/laravel-nginx:${{ env.IMAGE_VER }}

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export IMAGE_VER=${{ github.run_number }}
            cd ~/bigdashboard_pso && git checkout -b dev
            git pull origin dev
            sudo docker compose build
            sudo docker compose up -d
