name: Deploy Application

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/dockerfile/app.Dockerfile
          push: true
          tags: johanesrendy/laravel:${{ github.run_number }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/dockerfile/nginx.Dockerfile
          push: true
          tags: johanesrendy/laravel-nginx:${{ github.run_number }}

  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: "3.106.237.6"
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/bigdashboard_pso
            git checkout -b dev
            sed -i '' '$d' .env && echo "IMAGE_VER=${{ github.run_number }}" >> .env
            sudo nginx -t
            sudo service nginx restart
            sudo systemctl status nginx
            git pull origin dev
            sudo docker-compose --env-file .env down
            sudo docker compose --env-file .env build
            sudo docker compose --env-file .env up -d
            sudo docker logs laravel
            sudo docker logs nginx
