name: Laravel Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests-and-deploy:

    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - uses: actions/checkout@v4

    # Set up PHP (PHP 8.2)
    - name: Set up PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'

    # Check Current Directory
    - name: Check Current Directory
      run: pwd

    # Copy .env file (if not already present)
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Install project dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Generate application key
    - name: Generate key
      run: php artisan key:generate

    # Set permissions for directories
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Create SQLite Database file if not exists
    - name: Create Database (if needed)
      run: |
        mkdir -p database
        touch database/database.sqlite
        chmod 777 database/database.sqlite

    # Run tests (Unit and Feature tests) via PHPUnit/Pest
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

    # Deploy to EC2 Server
    - name: Deploy to EC2 Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.EC2_SERVER_IP }}
        SERVER_USER: ${{ secrets.EC2_SERVER_USER }}
      run: |
        # Save SSH private key and set permissions
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Connect to EC2 and deploy
        ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
          # Navigate to the Laravel project directory
          cd /var/www/laravel

          # Pull the latest changes from the main branch
          git pull origin main

          # Install Composer dependencies on the server
          composer install --no-interaction --prefer-dist

          # Run database migrations (force flag to avoid prompts)
          php artisan migrate --force

          # Clear and cache configurations and routes
          php artisan config:cache
          php artisan route:cache

          # Optimize Laravel application
          php artisan optimize
        EOF
