name: Quality Gate and Merge to Production

on:
  push:
    branches:
      - staging
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - staging

permissions:
  pull-requests: write
  contents: write  # Diperlukan untuk merge otomatis

jobs:
  quality-gate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pastikan semua riwayat tersedia

      - name: Run SonarCloud Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -s -u "${SONAR_TOKEN}:" \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=johanesrendy_bigdashboard_pso" \
          | jq -r '.projectStatus.status' > status.txt

          STATUS=$(cat status.txt)
          if [[ "$STATUS" != "OK" ]]; then
            echo "❌ Quality Gate Failed!"
            exit 1
          else
            echo "✅ Quality Gate Passed!"
          fi

  merge-to-production:
    needs: quality-gate-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge Staging to Production
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout production
          git merge --no-ff staging -m "Auto-merge staging to production after successful Quality Gate"
          git push origin production
